# Generated by a future TapAgents Codex renderer.

id = "{{agentId}}"
name = "{{agentName}}"
role = "{{agentRole}}"
description = "{{agentDescription}}"
source = "{{sourcePath}}"

[runtime]
adapter_id = "codex"
mode = "generated-files"

[instructions]
developer_instructions = "{{developerInstructions}}"
