# {{projectName}} Agents

Generated by a future TapAgents Codex renderer.

## Runtime

- Adapter: codex
- Mode: generated-files
- Contract: {{contractVersion}}

## Team

{{agentRoster}}

## Commands

{{commandRoster}}

## Operating Notes

{{operatingNotes}}
