# Generated by a future TapAgents Codex renderer.

[tap_agents]
adapter_id = "codex"
mode = "generated-files"
contract_version = "{{contractVersion}}"
plugin_beta_enabled = false

[workspace]
name = "{{projectName}}"
root = "{{projectRoot}}"
